#!/bin/bash -e

DIR=$(dirname "$(readlink $0)")
cd $DIR

case $1 in
  add-key)
    if [[ $# != 2 ]]
    then
      echo "Usage: socksd <add-key> PUBKEY"
      exit 0
    fi

    echo $2 >> home/socksproxy/.ssh/authorized_keys
    ;;

  build)
    docker build --no-cache -t socksd .
    ;;

  get-key)
    cat root/.ssh/id_ed25519.pub
    ;;

  init)
    mkdir -p {etc{,/ssh},home{,/socksproxy{,/.ssh}},root{,/.ssh}}
    cp sshd_config etc/ssh
    touch home/socksproxy/.ssh/authorized_keys
    ssh-keygen -t ed25519 -f root/.ssh/id_ed25519 -N ''
    ;;

  start)
    PORT=$(grep 'Port' etc/ssh/sshd_config | cut -d ' ' -f2)

    docker run \
      -d \
      --name socksd \
      -p $PORT:$PORT \
      -v $DIR/etc/ssh:/etc/ssh:ro \
      -v $DIR/home/socksproxy/.ssh:/home/socksproxy/.ssh \
      -v $DIR/root/.ssh:/root/.ssh:ro \
      socksd

    docker exec -it socksd passwd socksproxy
    ;;

  stop)
    docker rm -fv socksd
    ;;

  *)
    echo $'Usage: socksd <command> ARGS

Commands:
  add-key  PUBKEY  Add a public key to the authorized_keys file
  build            Build the Docker image
  get-key          Print the daemon\'s public key
  init             Setup directory structure and SSH keys
  start            Start a Docker container running the daemon
  stop             Stop the Docker container, remove it and the volumes'
    ;;
esac
