#!/bin/bash -e

DIR=$(dirname "$(readlink $0)")
cd $DIR

case $1 in
  add-proxy)
    if [[ $# != 2 ]]
    then
      echo "Usage: socksd <add-proxy> PUBKEY"
      exit
    fi

    echo $2 >> home/socksproxy/.ssh/authorized_keys
    ;;

  build)
    docker build --no-cache -t socksd .
    ;;

  get-key)
    cat root/.ssh/id_ed25519.pub
    ;;

  get-proxies)
    cat home/socksproxy/.ssh/authorized_keys
    ;;

  init)
    mkdir -p {etc{,/ssh},home{,/socksproxy{,/.ssh}},root{,/.ssh}}
    cp sshd_config etc/ssh
    touch home/socksproxy/.ssh/authorized_keys
    ssh-keygen -t ed25519 -f root/.ssh/id_ed25519 -N ''
    ;;

  rm-proxy)
    if [[ $# != 2 ]]
    then
      echo "Usage: socksd <rm-proxy> PUBKEY"
      exit
    fi

    grep -v $2 home/socksproxy/.ssh/authorized_keys > home/socksproxy/.ssh/authorized_keys
    ;;

  start)
    PORT=$(grep 'Port' etc/ssh/sshd_config | cut -d ' ' -f2)

    docker run \
      -d \
      --name socksd \
      -p $PORT:$PORT \
      --restart=always \
      -v $DIR/etc/ssh:/etc/ssh:ro \
      -v $DIR/home/socksproxy/.ssh:/home/socksproxy/.ssh \
      -v $DIR/root/.ssh:/root/.ssh:ro \
      socksd

    docker exec -it socksd passwd socksproxy
    ;;

  stop)
    docker rm -fv socksd
    ;;

  *)
    echo $'Usage: socksd <command> ARGS

Commands:
  add-proxy   PUBKEY  Add a proxy\'s public key to the authorized_keys file
  build               Build the Docker image
  get-key             Print the daemon\'s public key
  get-proxies         Print the authorized_keys file
  init                Setup directory structure and SSH keys
  rm-proxy    PUBKEY  Remove a proxy\'s public key from the authorized_keys file
  start               Start a Docker container running the daemon
  stop                Stop the Docker container, remove it and the volumes'
    ;;
esac
